name: Build and Test

on:
    push:
    pull_request:
        types:
            - opened
            - reopened
            - ready_for_review

env:
    CARGO_TERM_COLOR: always
    SCCACHE_GHA_ENABLED: "false"
    RUSTC_WRAPPER: "sccache"

jobs:
    # TODO: Add a job to run clippy
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Check formatting
              run: cargo fmt --all -- --check

    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install Rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  override: true
            - name: Run sccache-cache
              uses: mozilla-actions/sccache-action@v0.0.3
            - name: Build rust
              run: cargo build
            - name: Generate witness
              run: cargo test
